export const ActionTypes = {
  // Login
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  // Logout

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  // Signup
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  // Get All Adoption Posts
  GET_ALL_ADOPTION_POSTS_REQUEST: "GET_ALL_ADOPTION_POSTS_REQUEST",
  GET_ALL_ADOPTION_POSTS_SUCCESS: "GET_ALL_ADOPTION_POSTS_SUCCESS",
  GET_ALL_ADOPTION_POSTS_FAILURE: "GET_ALL_ADOPTION_POSTS_FAILURE",

  // Get Single Adoption Post
  GET_SINGLE_ADOPTION_POST_REQUEST: "GET_SINGLE_ADOPTION_POST_REQUEST",
  GET_SINGLE_ADOPTION_POST_SUCCESS: "GET_SINGLE_ADOPTION_POST_SUCCESS",
  GET_SINGLE_ADOPTION_POST_FAILURE: "GET_SINGLE_ADOPTION_POST_FAILURE",

  //get single rescue post
  GET_SINGLE_RESCUE_POST_REQUEST: "GET_SINGLE_RESCUE_POST_REQUEST",
  GET_SINGLE_RESCUE_POST_SUCCESS: "GET_SINGLE_RESCUE_POST_SUCCESS",
  GET_SINGLE_RESCUE_POST_FAILURE: "GET_SINGLE_RESCUE_POST_FAILURE",

  // Get All Rescue Posts
  GET_ALL_RESCUE_POSTS_REQUEST: "GET_ALL_RESCUE_POSTS_REQUEST",
  GET_ALL_RESCUE_POSTS_SUCCESS: "GET_ALL_RESCUE_POSTS_SUCCESS",
  GET_ALL_RESCUE_POSTS_FAILURE: "GET_ALL_RESCUE_POSTS_FAILURE",

  // Get All Volunteer Posts
  GET_ALL_VOLUNTEER_POSTS_REQUEST: "GET_ALL_VOLUNTEER_POSTS_REQUEST",
  GET_ALL_VOLUNTEER_POSTS_SUCCESS: "GET_ALL_VOLUNTEER_POSTS_SUCCESS",
  GET_ALL_VOLUNTEER_POSTS_FAILURE: "GET_ALL_VOLUNTEER_POSTS_FAILURE",

  // Get All Volunteer Posts
  GET_COMMENTS_REQUEST: "GET_COMMENTS_REQUEST",
  GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",
  GET_COMMENTS_FAILURE: "GET_COMMENTS_FAILURE",

  // Delete Comments In Rescue Posts
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAILURE: "DELETE_COMMENT_FAILURE",

  // Add Comments In Rescue Posts
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE",

  // Like In Rescue Posts
  LIKE_SUCCESS: "LIKE_SUCCESS",
  LIKE_FAILURE: "LIKE_FAILURE",

  TOGGLE_VOLUNTEER_MODE: "TOGGLE_VOLUNTEER_MODE",
};